[
   "_asyncToGenerator",
   "_regeneratorRuntime",
   "postMessageWithContentHeight",
   "delayShowChallengeData",
   "setRunStatus",
   "runChallenge",
   "_objectSpread2",
   "asString",
   "sendCandidate",
   "handleMobile",
   "handleWeb"
]